### ISSUE TITLE
使用zookeeper注册发现的方式拉取指标，报下面的错

### ISSUE THREAD

**Issue by zouchangzhen** [MyLanPangzi/flink-demo#11]
023-09-05 11:48:18,678 ERROR org.apache.flink.shaded.curator5.org.apache.curator.ConnectionState [] - Authentication failed
2023-09-05 11:48:18,679 INFO  org.apache.flink.shaded.zookeeper3.org.apache.zookeeper.ClientCnxn [] - Socket connection established, initiating session, client: /10.83.192.23:59229, server: szzb-bg-uat-etl-08/10.83.192.8:2181
2023-09-05 11:48:18,679 INFO  org.apache.flink.shaded.curator5.org.apache.curator.framework.imps.CuratorFrameworkImpl [] - Default schema
2023-09-05 11:48:18,684 INFO  org.apache.flink.shaded.zookeeper3.org.apache.zookeeper.ClientCnxn [] - Session establishment complete on server szzb-bg-uat-etl-08/10.83.192.8:2181, sessionid = 0x300000c4e1ce1ed, negotiated timeout = 600000
2023-09-05 11:48:18,686 INFO  org.apache.flink.shaded.curator5.org.apache.curator.framework.state.ConnectionStateManager [] - State change: CONNECTED
2023-09-05 11:48:18,695 INFO  com.zcz.flink.prometheus.sd.BaseZookeeperServiceDiscovery [] - zk stat: null
2023-09-05 11:48:18,695 INFO  com.zcz.flink.prometheus.sd.BaseZookeeperServiceDiscovery [] - zk register...
2023-09-05 11:48:18,701 INFO  com.zcz.flink.prometheus.sd.BaseZookeeperServiceDiscovery [] - zk make data...
2023-09-05 11:48:18,703 INFO  com.zcz.flink.prometheus.sd.BaseZookeeperServiceDiscovery [] - zk make data...end
2023-09-05 11:48:18,709 INFO  org.apache.flink.shaded.zookeeper3.org.apache.zookeeper.ClientCnxn [] - Unable to read additional data from server sessionid 0x300000c4e1ce1ed, likely server has closed socket, closing socket connection and attempting reconnect
2023-09-05 11:48:18,709 ERROR com.zcz.flink.prometheus.sd.BaseZookeeperServiceDiscovery [] - zk register err
org.apache.flink.shaded.zookeeper3.org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /flink-metrics/jm/sdp_uat_test_test_zk
	at org.apache.flink.shaded.zookeeper3.org.apache.zookeeper.KeeperException.create(KeeperException.java:106) ~[flink-shaded-zookeeper-3.5.9.jar:3.5.9-15.0]
	at org.apache.flink.shaded.zookeeper3.org.apache.zookeeper.KeeperException.create(KeeperException.java:54) ~[flink-shaded-zookeeper-3.5.9.jar:3.5.9-15.0]
	at org.apache.flink.shaded.zookeeper3.org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1637) ~[flink-shaded-zookeeper-3.5.9.jar:3.5.9-15.0]
	at org.apache.flink.shaded.curator5.org.apache.curator.framework.imps.CreateBuilderImpl$18.call(CreateBuilderImpl.java:1216) ~[flink-shaded-zookeeper-3.5.9.jar:3.5.9-15.0]
	at org.apache.flink.shaded.curator5.org.apache.curator.framework.imps.CreateBuilderImpl$18.call(CreateBuilderImpl.java:1193) ~[flink-shaded-zookeeper-3.5.9.jar:3.5.9-15.0]
	at org.apache.flink.shaded.curator5.org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:93) ~[flink-shaded-zookeeper-3.5.9.jar:3.5.9-15.0]
	at org.apache.flink.shaded.curator5.org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:1190) ~[flink-shaded-zookeeper-3.5.9.jar:3.5.9-15.0]
	at org.apache.flink.shaded.curator5.org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:605) ~[flink-shaded-zookeeper-3.5.9.jar:3.5.9-15.0]
	at org.apache.flink.shaded.curator5.org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:595) ~[flink-shaded-zookeeper-3.5.9.jar:3.5.9-15.0]
	at org.apache.flink.shaded.curator5.org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:48) ~[flink-shaded-zookeeper-3.5.9.jar:3.5.9-15.0]
	at com.zcz.flink.prometheus.sd.BaseZookeeperServiceDiscovery.registerNode(BaseZookeeperServiceDiscovery.java:61) ~[flink-zookeeper-prometheus-1.0-SNAPSHOT.jar:?]
	at com.zcz.flink.prometheus.sd.BaseZookeeperServiceDiscovery.register(BaseZookeeperServiceDiscovery.java:34) ~[flink-zookeeper-prometheus-1.0-SNAPSHOT.jar:?]
	at com.zcz.flink.prometheus.AutoServiceDiscoveryPrometheusReporter.open(AutoServiceDiscoveryPrometheusReporter.java:57) ~[flink-zookeeper-prometheus-1.0-SNAPSHOT.jar:?]
	at org.apache.flink.runtime.metrics.ReporterSetup.createReporterSetup(ReporterSetup.java:186) ~[flink-dist-1.16.1.jar:1.16.1]
	at org.apache.flink.runtime.metrics.ReporterSetup.lambda$setupReporters$2(ReporterSetup.java:347) ~[flink-dist-1.16.1.jar:1.16.1]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_131]
	at org.apache.flink.runtime.metrics.ReporterSetup.setupReporters(ReporterSetup.java:342) ~[flink-dist-1.16.1.jar:1.16.1]
	at org.apache.flink.runtime.metrics.ReporterSetup.fromConfiguration(ReporterSetup.java:209) ~[flink-dist-1.16.1.jar:1.16.1]
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.createMetricRegistry(ClusterEntrypoint.java:458) ~[flink-dist-1.16.1.jar:1.16.1]
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.initializeServices(ClusterEntrypoint.java:397) ~[flink-dist-1.16.1.jar:1.16.1]
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.runCluster(ClusterEntrypoint.java:282) ~[flink-dist-1.16.1.jar:1.16.1]
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.lambda$startCluster$1(ClusterEntrypoint.java:232) ~[flink-dist-1.16.1.jar:1.16.1]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	at javax.security.auth.Subject.doAs(Subject.java:422) [?:1.8.0_131]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729) [hadoop-common-3.1.1.jar:?]
	at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41) [flink-dist-1.16.1.jar:1.16.1]
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.startCluster(ClusterEntrypoint.java:229) [flink-dist-1.16.1.jar:1.16.1]
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.runClusterEntrypoint(ClusterEntrypoint.java:729) [flink-dist-1.16.1.jar:1.16.1]
	at org.apache.flink.yarn.entrypoint.YarnApplicationClusterEntryPoint.main(YarnApplicationClusterEntryPoint.java:112) [flink-dist-1.16.1.jar:1.16.1]
2023-09-05 11:48:18,726 ERROR org.apache.flink.runtime.metrics.ReporterSetup               [] - Could not instantiate metrics reporter prom. Metrics might not be exposed/reported.

**Comment by MyLanPangzi** [comment]
版本不对吧，zk3.4的？
